name: CI-CD Workflow

on:
  workflow_call:
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}  # Passing the secret to the called workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
